AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false